import React, { useState } from "react";
import { CreditCard, Landmark, Repeat2, Scale } from "lucide-react";
import TopBar from "./TopBar";
import { toCents } from "../financial-engine/index.js";

const cents = (value) => toCents(Number(String(value || 0).replace(/\./g, "").replace(",", ".")));
const Field = ({ label, children }) => <label className="block text-xs font-semibold">{label}{children}</label>;
const Input = (props) => <input {...props} className="w-full rounded-xl border px-3 py-2.5 mt-1" />;
const Select = ({ children, ...props }) => <select {...props} className="w-full rounded-xl border px-3 py-2.5 mt-1">{children}</select>;

function Editor({ title, icon: Icon, count, children }) {
  return <details className="rounded-3xl p-4" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><summary className="flex items-center gap-3 cursor-pointer"><div className="w-10 h-10 rounded-2xl flex items-center justify-center" style={{ background: "var(--primary-lt)" }}><Icon size={20} color="var(--primary)" /></div><div className="flex-1"><p className="font-semibold text-sm">{title}</p><p className="text-xs" style={{ color: "var(--ink-soft)" }}>{count} cadastrado(s)</p></div></summary><div className="pt-4">{children}</div></details>;
}

export default function FinanceManagerScreen({ financialData, onBack, onSaveAccount, onSaveCard, onSavePurchase, onSaveRecurring, onSaveDebt }) {
  const accounts = financialData.accounts.filter((item) => item.active !== false);
  const [error, setError] = useState("");
  const [ok, setOk] = useState("");
  const [account, setAccount] = useState({ id: null, name: "", type: "checking", opening: "0", reserved: false });
  const [card, setCard] = useState({ id: null, name: "", limit: "", closingDay: 20, dueDay: 28, lastFour: "" });
  const [purchase, setPurchase] = useState({ cardId: financialData.creditCards[0]?.id ?? "", description: "", total: "", installments: 1, firstInvoiceMonth: new Date().toISOString().slice(0, 7), date: new Date().toISOString().slice(0, 10) });
  const [recurring, setRecurring] = useState({ id: null, name: "", type: "expense", amount: "", dueDay: 10, startDate: new Date().toISOString().slice(0, 10), accountId: accounts[0]?.id ?? "", categoryId: "outros" });
  const [debt, setDebt] = useState({ id: null, name: "", balance: "", installment: "", remaining: 1, interest: "", dueDay: 10, accountId: accounts[0]?.id ?? "" });
  const run = (callback, reset) => (event) => { event.preventDefault(); setError(""); setOk(""); try { const result = callback(); if (!result.ok) throw new Error(result.error); setOk("Dados salvos com segurança."); reset?.(); } catch (caught) { setError(caught.message); } };

  return <div className="pb-4"><TopBar title="Cadastros financeiros" subtitle="Contas, cartões, recorrências e dívidas" onBack={onBack} /><div className="px-5 space-y-3">
    {error && <p className="rounded-2xl p-3 text-xs" style={{ background: "#FDECEC", color: "var(--accent)" }}>{error}</p>}{ok && <p className="rounded-2xl p-3 text-xs" style={{ background: "var(--primary-lt)", color: "var(--primary)" }}>{ok}</p>}
    <Editor title="Contas e carteiras" icon={Landmark} count={accounts.length}><form className="space-y-3" onSubmit={run(() => onSaveAccount({ name: account.name, type: account.type, openingBalanceCents: cents(account.opening), reserved: account.reserved }), () => setAccount({ name: "", type: "checking", opening: "0", reserved: false }))}><Field label="Nome"><Input required value={account.name} onChange={(e) => setAccount({ ...account, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Tipo"><Select value={account.type} onChange={(e) => setAccount({ ...account, type: e.target.value })}><option value="checking">Conta corrente</option><option value="cash">Dinheiro</option><option value="digital_wallet">Carteira digital</option><option value="savings">Poupança</option><option value="investment">Investimento</option><option value="other">Outro</option></Select></Field><Field label="Saldo inicial"><Input inputMode="decimal" value={account.opening} onChange={(e) => setAccount({ ...account, opening: e.target.value })} /></Field></div><label className="flex gap-2 text-xs"><input type="checkbox" checked={account.reserved} onChange={(e) => setAccount({ ...account, reserved: e.target.checked })} /> Valor reservado</label><button className="w-full rounded-xl p-3 font-semibold" style={{ background: "var(--primary)", color: "white" }}>Adicionar conta</button></form></Editor>
    <Editor title="Cartões de crédito" icon={CreditCard} count={financialData.creditCards.length}><form className="space-y-3" onSubmit={run(() => onSaveCard({ name: card.name, limitCents: cents(card.limit), closingDay: Number(card.closingDay), dueDay: Number(card.dueDay), lastFour: card.lastFour }), () => setCard({ name: "", limit: "", closingDay: 20, dueDay: 28, lastFour: "" }))}><Field label="Nome do cartão"><Input required value={card.name} onChange={(e) => setCard({ ...card, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Limite"><Input required inputMode="decimal" value={card.limit} onChange={(e) => setCard({ ...card, limit: e.target.value })} /></Field><Field label="Últimos 4 dígitos"><Input maxLength="4" inputMode="numeric" value={card.lastFour} onChange={(e) => setCard({ ...card, lastFour: e.target.value })} /></Field><Field label="Fechamento"><Input required type="number" min="1" max="31" value={card.closingDay} onChange={(e) => setCard({ ...card, closingDay: e.target.value })} /></Field><Field label="Vencimento"><Input required type="number" min="1" max="31" value={card.dueDay} onChange={(e) => setCard({ ...card, dueDay: e.target.value })} /></Field></div><button className="w-full rounded-xl p-3 font-semibold" style={{ background: "var(--primary)", color: "white" }}>Adicionar cartão</button></form>
      {financialData.creditCards.length > 0 && <form className="space-y-3 mt-5 pt-4" style={{ borderTop: "1px solid var(--line)" }} onSubmit={run(() => onSavePurchase({ cardId: purchase.cardId, description: purchase.description, totalCents: cents(purchase.total), installmentCount: Number(purchase.installments), firstInvoiceMonth: purchase.firstInvoiceMonth, date: purchase.date }), () => setPurchase({ ...purchase, description: "", total: "", installments: 1 }))}><p className="font-semibold text-sm">Registrar compra parcelada</p><Field label="Cartão"><Select value={purchase.cardId} onChange={(e) => setPurchase({ ...purchase, cardId: e.target.value })}>{financialData.creditCards.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Descrição"><Input required value={purchase.description} onChange={(e) => setPurchase({ ...purchase, description: e.target.value })} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Valor total"><Input required inputMode="decimal" value={purchase.total} onChange={(e) => setPurchase({ ...purchase, total: e.target.value })} /></Field><Field label="Parcelas"><Input required type="number" min="1" max="120" value={purchase.installments} onChange={(e) => setPurchase({ ...purchase, installments: e.target.value })} /></Field><Field label="Data"><Input required type="date" value={purchase.date} onChange={(e) => setPurchase({ ...purchase, date: e.target.value })} /></Field><Field label="Primeira fatura"><Input required type="month" value={purchase.firstInvoiceMonth} onChange={(e) => setPurchase({ ...purchase, firstInvoiceMonth: e.target.value })} /></Field></div><button className="w-full rounded-xl p-3 font-semibold" style={{ background: "var(--primary)", color: "white" }}>Registrar compra</button></form>}</Editor>
    <Editor title="Receitas e contas recorrentes" icon={Repeat2} count={financialData.recurringEntries.length}><form className="space-y-3" onSubmit={run(() => onSaveRecurring({ name: recurring.name, type: recurring.type, amountCents: cents(recurring.amount), dueDay: Number(recurring.dueDay), startDate: recurring.startDate, accountId: recurring.accountId, categoryId: recurring.categoryId }), () => setRecurring({ ...recurring, name: "", amount: "" }))}><Field label="Nome"><Input required value={recurring.name} onChange={(e) => setRecurring({ ...recurring, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Tipo"><Select value={recurring.type} onChange={(e) => setRecurring({ ...recurring, type: e.target.value })}><option value="expense">Conta a pagar</option><option value="income">Receita a receber</option></Select></Field><Field label="Valor"><Input required inputMode="decimal" value={recurring.amount} onChange={(e) => setRecurring({ ...recurring, amount: e.target.value })} /></Field><Field label="Dia"><Input required type="number" min="1" max="31" value={recurring.dueDay} onChange={(e) => setRecurring({ ...recurring, dueDay: e.target.value })} /></Field><Field label="Início"><Input required type="date" value={recurring.startDate} onChange={(e) => setRecurring({ ...recurring, startDate: e.target.value })} /></Field></div><Field label="Conta"><Select value={recurring.accountId} onChange={(e) => setRecurring({ ...recurring, accountId: e.target.value })}>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><button className="w-full rounded-xl p-3 font-semibold" style={{ background: "var(--primary)", color: "white" }}>Adicionar recorrência</button></form></Editor>
    <Editor title="Dívidas e financiamentos" icon={Scale} count={financialData.debts.length}><form className="space-y-3" onSubmit={run(() => onSaveDebt({ name: debt.name, balanceCents: cents(debt.balance), installmentCents: cents(debt.installment), remainingInstallments: Number(debt.remaining), interestRateMonthly: debt.interest === "" ? null : Number(String(debt.interest).replace(",", ".")), dueDay: Number(debt.dueDay), accountId: debt.accountId }), () => setDebt({ ...debt, name: "", balance: "", installment: "", remaining: 1, interest: "" }))}><Field label="Nome"><Input required value={debt.name} onChange={(e) => setDebt({ ...debt, name: e.target.value })} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Saldo devedor"><Input required inputMode="decimal" value={debt.balance} onChange={(e) => setDebt({ ...debt, balance: e.target.value })} /></Field><Field label="Parcela"><Input required inputMode="decimal" value={debt.installment} onChange={(e) => setDebt({ ...debt, installment: e.target.value })} /></Field><Field label="Parcelas restantes"><Input required type="number" min="0" value={debt.remaining} onChange={(e) => setDebt({ ...debt, remaining: e.target.value })} /></Field><Field label="Juros % a.m."><Input inputMode="decimal" value={debt.interest} onChange={(e) => setDebt({ ...debt, interest: e.target.value })} /></Field><Field label="Vencimento"><Input required type="number" min="1" max="31" value={debt.dueDay} onChange={(e) => setDebt({ ...debt, dueDay: e.target.value })} /></Field><Field label="Conta de pagamento"><Select value={debt.accountId} onChange={(e) => setDebt({ ...debt, accountId: e.target.value })}>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field></div><button className="w-full rounded-xl p-3 font-semibold" style={{ background: "var(--primary)", color: "white" }}>Adicionar dívida</button></form></Editor>
  </div></div>;
}
