import React, { useState } from "react";
import { Download, RotateCcw, ShieldCheck, Upload } from "lucide-react";
import TopBar from "./TopBar";
import { exportFinancialBackup, importFinancialBackup } from "../financial-engine/index.js";

export default function FinancialBackupScreen({ financialData, onBack, onRestoreAutomatic, onImport }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  function download() { const blob = new Blob([exportFinancialBackup(financialData)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `cofrinho-financeiro-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage("Backup financeiro exportado."); }
  async function loadFile(event) { const file = event.target.files?.[0]; if (!file) return; setError(""); try { const restored = importFinancialBackup(await file.text()); const result = onImport(restored); if (!result.ok) throw new Error(result.error); setMessage("Backup importado e validado."); } catch (caught) { setError(caught.message); } finally { event.target.value = ""; } }
  function automatic() { setError(""); const result = onRestoreAutomatic(); if (!result.ok) setError(result.error); else setMessage("Versão anterior restaurada."); }
  return <div className="pb-4"><TopBar title="Proteção financeira" subtitle="Backup integral e recuperação" onBack={onBack} /><div className="px-5 space-y-4"><div className="rounded-3xl p-5" style={{ background: "var(--primary-lt)" }}><ShieldCheck size={28} color="var(--primary)" /><h2 className="font-display text-xl font-semibold mt-2">Seus dados sob seu controle</h2><p className="text-xs mt-2" style={{ color: "var(--ink-soft)" }}>O arquivo inclui contas, movimentações, cartões, faturas, recorrências, dívidas, metas e atividades.</p></div>{message && <p className="rounded-2xl p-3 text-xs" style={{ background: "var(--primary-lt)", color: "var(--primary)" }}>{message}</p>}{error && <p className="rounded-2xl p-3 text-xs" style={{ background: "#FDECEC", color: "var(--accent)" }}>{error}</p>}<button onClick={download} className="w-full rounded-2xl p-4 flex justify-center gap-2 font-semibold" style={{ background: "var(--primary)", color: "white" }}><Download size={19} />Exportar backup integral</button><label className="w-full rounded-2xl p-4 flex justify-center gap-2 font-semibold cursor-pointer" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><Upload size={19} />Importar backup<input type="file" accept="application/json,.json" onChange={loadFile} className="sr-only" /></label><button onClick={automatic} className="w-full rounded-2xl p-4 flex justify-center gap-2 font-semibold" style={{ background: "var(--accent-lt)", color: "var(--accent)" }}><RotateCcw size={19} />Restaurar versão anterior</button></div></div>;
}
