import React, { useMemo } from "react";
import { AlertTriangle, CalendarClock, Landmark, Repeat2, Scale, TrendingUp } from "lucide-react";
import TopBar from "./TopBar";
import { compareDebtStrategies, forecastFinancialFuture, fromCents } from "../financial-engine/index.js";
import { brl } from "../lib/helpers";

const STATUS_LABELS = { normal: "Em dia", late: "Atrasada", negotiation: "Em negociação" };

export default function PlanningScreen({ financialData, onBack }) {
  const today = new Date().toISOString().slice(0, 10);
  const forecasts = useMemo(() => [30, 60, 90].map((days) => forecastFinancialFuture(financialData, today, days)), [financialData, today]);
  const strategies = useMemo(() => compareDebtStrategies(financialData.debts), [financialData.debts]);
  const hasPlanningData = financialData.recurringEntries.length > 0 || financialData.debts.length > 0 || financialData.creditCards.length > 0;
  return (
    <div className="pb-4">
      <TopBar title="Planejamento" subtitle="Recorrências, dívidas e próximos 90 dias" onBack={onBack} />
      <div className="px-5 space-y-5">
        <section aria-labelledby="forecast-title"><div className="flex items-center gap-2 mb-3"><TrendingUp size={20} color="var(--primary)" /><h2 id="forecast-title" className="font-display text-xl font-semibold">Previsões</h2></div><div className="grid grid-cols-3 gap-2">{forecasts.map((forecast) => <div key={forecast.days} className="rounded-2xl p-3 text-center" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><p className="text-[10px] font-semibold" style={{ color: "var(--ink-soft)" }}>{forecast.days} dias</p><p className="text-xs font-semibold mt-1" style={{ color: forecast.projectedBalanceCents < 0 ? "var(--accent)" : "var(--primary)" }}>{brl(fromCents(forecast.projectedBalanceCents))}</p><p className="text-[9px] mt-1" style={{ color: "var(--ink-soft)" }}>{forecast.events.length} compromisso(s)</p></div>)}</div>{!hasPlanningData ? <div className="rounded-2xl p-3 flex gap-2 mt-3" style={{ background: "var(--primary-lt)" }}><CalendarClock size={17} color="var(--primary)" /><p className="text-xs" style={{ color: "var(--ink-soft)" }}>A previsão ainda repete o saldo atual porque recorrências, dívidas e cartões não foram informados.</p></div> : null}</section>

        <section aria-labelledby="recurring-title"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Repeat2 size={20} color="var(--primary)" /><h2 id="recurring-title" className="font-display text-xl font-semibold">Recorrências</h2></div><span className="text-xs" style={{ color: "var(--ink-soft)" }}>{financialData.recurringEntries.length}</span></div>{financialData.recurringEntries.length === 0 ? <div className="rounded-3xl p-5 text-center" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><p className="font-semibold text-sm">Nenhuma recorrência informada</p><p className="text-xs mt-1" style={{ color: "var(--ink-soft)" }}>Salário, pecúlio e contas mensais aparecerão aqui.</p></div> : <div className="space-y-2">{financialData.recurringEntries.map((entry) => <article key={entry.id} className="rounded-2xl p-3 flex items-center gap-3" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: "var(--primary-lt)" }}><Repeat2 size={17} color="var(--primary)" /></div><div className="flex-1"><p className="font-semibold text-sm">{entry.name}</p><p className="text-[10px]" style={{ color: "var(--ink-soft)" }}>Todo dia {entry.dueDay}</p></div><p className="text-sm font-semibold" style={{ color: entry.type === "income" ? "var(--primary)" : "var(--accent)" }}>{entry.type === "income" ? "+" : "−"}{brl(fromCents(entry.amountCents))}</p></article>)}</div>}</section>

        <section aria-labelledby="debts-title"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Landmark size={20} color="var(--primary)" /><h2 id="debts-title" className="font-display text-xl font-semibold">Dívidas</h2></div><span className="text-xs" style={{ color: "var(--ink-soft)" }}>{financialData.debts.length}</span></div>{financialData.debts.length === 0 ? <div className="rounded-3xl p-5 text-center" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><p className="font-semibold text-sm">Nenhuma dívida informada</p><p className="text-xs mt-1" style={{ color: "var(--ink-soft)" }}>Financiamentos e empréstimos aparecerão aqui após sua confirmação.</p></div> : <div className="space-y-2">{financialData.debts.map((debt) => <article key={debt.id} className="rounded-2xl p-3" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><div className="flex items-start gap-3"><div className="flex-1"><p className="font-semibold text-sm">{debt.name}</p><p className="text-[10px] mt-1" style={{ color: debt.status === "late" ? "var(--accent)" : "var(--ink-soft)" }}>{STATUS_LABELS[debt.status]} · {debt.remainingInstallments} parcela(s)</p></div><p className="font-display font-semibold">{brl(fromCents(debt.balanceCents))}</p></div><div className="flex justify-between mt-3 pt-3" style={{ borderTop: "1px solid var(--line)" }}><p className="text-xs" style={{ color: "var(--ink-soft)" }}>Parcela {brl(fromCents(debt.installmentCents))}</p><p className="text-xs" style={{ color: "var(--ink-soft)" }}>{debt.interestRateMonthly != null ? `${debt.interestRateMonthly}% a.m.` : "Juros não informados"}</p></div></article>)}</div>}</section>

        {strategies.smallestBalance ? <section className="rounded-3xl p-4" style={{ background: "var(--primary-lt)" }}><div className="flex items-center gap-2"><Scale size={19} color="var(--primary)" /><h2 className="font-semibold text-sm">Comparação de estratégias</h2></div><div className="grid grid-cols-2 gap-3 mt-3"><div><p className="text-[10px] uppercase" style={{ color: "var(--ink-soft)" }}>Menor dívida</p><p className="text-sm font-semibold mt-1">{strategies.smallestBalance.name}</p></div><div><p className="text-[10px] uppercase" style={{ color: "var(--ink-soft)" }}>Maior juro</p><p className="text-sm font-semibold mt-1">{strategies.highestInterest.name}</p></div></div><div className="flex gap-2 mt-3"><AlertTriangle size={16} color="var(--accent)" /><p className="text-[10px]" style={{ color: "var(--ink-soft)" }}>A melhor escolha dependerá também da sua liquidez e das condições reais de antecipação.</p></div></section> : null}
      </div>
    </div>
  );
}
