import React, { useState } from "react";
import { CheckCircle2, ShieldAlert } from "lucide-react";
import TopBar from "./TopBar";
import { analyzePurchaseDecision, fromCents, toCents } from "../financial-engine/index.js";
import { brl } from "../lib/helpers";

export default function PurchaseDecisionScreen({ financialData, onBack }) {
  const [form, setForm] = useState({ itemName: "", installment: "", count: 1 });
  const [result, setResult] = useState(null); const [error, setError] = useState("");
  function submit(event) { event.preventDefault(); setError(""); try { setResult(analyzePurchaseDecision(financialData, new Date().toISOString().slice(0, 10), { itemName: form.itemName, installmentCents: toCents(Number(form.installment.replace(/\./g, "").replace(",", "."))), installmentCount: Number(form.count) })); } catch (caught) { setError(caught.message); } }
  return <div className="pb-4"><TopBar title="Posso comprar?" subtitle="Decisão baseada nos seus números" onBack={onBack} /><div className="px-5 space-y-4"><form onSubmit={submit} className="rounded-3xl p-4 space-y-3" style={{ background: "var(--surface)", border: "1px solid var(--line)" }}><label className="block text-xs font-semibold">O que você quer comprar?<input required value={form.itemName} onChange={(e) => setForm({ ...form, itemName: e.target.value })} className="w-full rounded-xl border px-3 py-3 mt-1" placeholder="Ex.: PS5" /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Valor da parcela<input required inputMode="decimal" value={form.installment} onChange={(e) => setForm({ ...form, installment: e.target.value })} className="w-full rounded-xl border px-3 py-3 mt-1" /></label><label className="text-xs font-semibold">Parcelas<input required type="number" min="1" max="120" value={form.count} onChange={(e) => setForm({ ...form, count: e.target.value })} className="w-full rounded-xl border px-3 py-3 mt-1" /></label></div><button className="w-full rounded-xl p-3 font-semibold" style={{ background: "var(--primary)", color: "white" }}>Analisar compra</button></form>{error && <p className="rounded-2xl p-3 text-xs" style={{ background: "#FDECEC", color: "var(--accent)" }}>{error}</p>}{result && <section className="rounded-3xl p-5" style={{ background: result.recommendation === "can_buy" ? "var(--primary-lt)" : "var(--accent-lt)" }}>{result.recommendation === "can_buy" ? <CheckCircle2 size={28} color="var(--primary)" /> : <ShieldAlert size={28} color="var(--accent)" />}<h2 className="font-display text-2xl font-semibold mt-2">{result.recommendation === "can_buy" ? "A compra cabe hoje" : "Melhor não comprar agora"}</h2><p className="text-sm mt-2">Dinheiro livre: <strong>{brl(fromCents(result.freeMoneyCents))}</strong></p><p className="text-sm">Parcela: <strong>{brl(fromCents(result.installmentCents))}</strong></p><p className="text-sm">Livre após a parcela no mês: <strong>{brl(fromCents(result.monthlyCapacityAfterCents))}</strong></p><p className="text-xs mt-3" style={{ color: "var(--ink-soft)" }}>Custo total: {brl(fromCents(result.totalPurchaseCents))}. Projeção verificada em 30, 60 e 90 dias.</p></section>}</div></div>;
}
